### ISSUE TITLE
DAC output impedance

### ISSUE THREAD

**Issue by fsmMLK** [moefh/esp32-loser#1]
Do you see ghosting or ringing on the monitor?

I see a possible problem with keeping the 220+470+75R resistors. You are not matching the output impedance seen by the VGA display with its input impedance (75R). The TOTAL equivalent resistance observed from the 'OUTPUT' lead must match the input impedance of your VGA display. Otherwise you might get reflections and  see ghosting or ringing on the screen, specially if using CRT monitors.

In your case, the total output impedance is 470//220//75=50R (where // stands for parallel association). Remember that you must replace all voltage sources (GPIO) with short circuits to GND ('cause physics). Then you will see that all 3 resistores are in parallel .

Additionally, from my (crude) calculations, you might have GPIO currents ~12mA in some situations, which is very close to the max ESP32 GPIO can handle (12mA?). It might be a good idea to keep a short distance from the limit ( just in case).

**Comment by fsmMLK** [comment]
also,
You are basically using the simplest form of Binary Weighted DAC (no operational amplifier to isolate the stages.)

If later you decide to increase the number of bits, you might have problems adjusting the resistors since they usually follow a power law R_n~=R_0^n.  (https://www.electronics-tutorials.ws/combination/digital-to-analogue-converter.html)

A better (easier) solution is to implement a R-2R ladder strategy (https://www.electronics-tutorials.ws/combination/r-2r-dac.html). It is still quite simple and requires only 2 resistor values.

The next (far) step is to add an operational amplifier to the circuit to deal with the input output impedance ballet.

**Comment by moefh** [comment]
Hello!

I see no ghosting or ringing in the output image, even in fine high-contrast parts (like white text on dark background).

I think you're right about the high current use, I didn't check the ESP32 max current (I thought it would be something like 20mA like the Arduino). From my calculations, 280R/560R on the pins and 130R to the ground would give an output impedance of about 76R and reduce the current to 10mA at most, so I think that would be ideal? Sadly I don't have 130R right now, I'll have to get some.

I think another thing to take into account is that the ESP32 will have some internal resistance on the output pins, I imagine it would become important when increasing the number of bits. [This project](https://github.com/obstruse/pico-composite8) for example is using 8 bits (composite video, but I imagine the electric characteristic would be very similar to VGA), and they mention the output resistance on the Raspberry Pi Pico pins is about 40R. At that point, I think it probably would be best to use an op amp as you mentioned. I have no idea if there's a cheap enough op amp capable of working at 12MHz, though.

**Comment by fsmMLK** [comment]
1-) There is no consensus on max current: =S
a) the max current might be 40mA or 20mA (depends on the GPIO you are using). But it [depends](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf) , Table 13,  page 45. Look for I_OH

b) However [people](https://esp32.com/viewtopic.php?t=2027) are saying to not trust these values. 

2-) anything >20mA is overkill. I would stick with <12 unless you have problems. (Do not fix problems you don't have yet)

3-) Go for 1% resistors. They are cheap if you buy from aliexpress or similar

4-) GPIO output impedance DO matter when other resistors are of the same order of magnitude. They must be added in series with the associated resistor (280 or 560) as presented in the link you sent. I could not find the output resistance of  the pins from the datasheet. The best way to find out is to [measure yourself](http://www.zen22142.zen.co.uk/Theory/inzoz.htm). I would use as load R_L a resistor with similar total resistance seen by the pin (100R to 1k). The link is in fact measuring the Thevenin equivalent, valid for linear circuits. Your pin is NOT completely linear (black magic inside), so measure not too far from operation conditions to be safe.

5-) When you want to move to 3x8bit DAC solution must be modified. Probably R-2R ladder + output buffer + output resistor
https://electronics.stackexchange.com/questions/367797/resistor-dac-and-buffer-for-vga-output
https://itectec.com/electrical/electronic-resistor-dac-and-buffer-for-vga-output/

6-) or, in case you are not interested in creating your own DAC, there are fairly cheap IC solutions 
https://www.analog.com/media/en/technical-documentation/data-sheets/ADV7120.pdf
https://www.rocelec.com/part/ANAADV7125KST50
You might even salvage an IC from an old video card board

**Comment by moefh** [comment]
Thank you for the info and the links!

I'll go with the 280R/560R/130R 1% solution for now, but I'll keep the other stuff in mind for future projects.
